---
title: "Process relations from Wikidata"
author:
  - name: Satoshi Kume
date: "`r Sys.Date()`"
graphics: no
package: agGraphSearch, knitr, SPARQL
output:
  BiocStyle::html_document:
  toc_float: true
vignette: >
  %\VignetteEncoding{UTF-8}
  %\VignetteDepends{agGraphSearch}
  %\VignetteIndexEntry{Process relations from Wikidata}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

```{r style, echo = FALSE, results = 'asis', message=FALSE}
BiocStyle::markdown()
```

**Last modified:** `r file.info("agGraphSearch-WF-002.Rmd")$mtime`<br />
**Compiled**: `r date()`

# Getting started

Once `r Rpackage("agGraphSearch")` is installed, it can be loaded by the following command.

```{r library, message=FALSE}
library("agGraphSearch")
```

This workflow can be skipped. The next workflow should be started. 

# prepare QIDs

```{r echo=TRUE, eval=FALSE}
rm(list=ls()[!(ls() %in% c("df", "Wikilabels"))])

#変化 (wd:Q1150070)
#過程 (wd:Q3249551)
#行為 (wd:Q1914636)
#物理的プロセス (wd:Q17320256)
#プロセス機能 (wd:Q900800)
#物理現象 (wd:Q1293220)
#熱力学過程 (wd:Q213016)
#技術 (wd:Q2695280)
#製造プロセス  (wd:Q1408288)
#工学的プロセス (wd:Q14359196)
#自然過程 (wd:Q13878858)
#計画プロセス (wd:Q104637332)
#材料加工 (wd:Q104637425)
#成形プロセス (wd:Q1363994)
#化学過程 (wd:Q2281940)
#化学反応 (wd:Q36534)
#物質の変換 (wd:Q3537517)
#重合反応 (wd:Q181898)
#連鎖反応 (化学反応) (wd:Q1739960)

#Process
#上位
QIDup <- c("wd:Q1150070", "wd:Q3249551", "wd:Q1914636", 
         "wd:Q17320256", "wd:Q900800", "wd:Q1293220", 
         "wd:Q213016", "wd:Q2695280", "wd:Q1408288",
         "wd:Q10843872", "wd:Q13878858", "wd:Q104637332",
         "wd:Q104637425", "wd:Q1363994", "wd:Q2281940",
         "wd:Q36534", "wd:Q3537517", "wd:Q181898", "wd:Q1739960")

#下位
#QIDdown <- c("wd:Q17320256")
#QIDdown <- c("wd:Q10843872")
#QIDdown <- c("wd:Q900800")
#QIDdown <- c("wd:Q13878858")
#QIDdown <- c("wd:Q3537517")
#QIDdown <- c("wd:Q36534")

#下位リスト
QIDdown <- unique(c("wd:Q471702",  "wd:Q213016",  "wd:Q15211908", "wd:Q108000", "wd:Q3240978",
             "wd:Q210028",  "wd:Q29652844", "wd:Q2035846", "wd:Q215328",
             "wd:Q1363994", "wd:Q1651044",  "wd:Q747713", "wd:Q720899", "wd:Q720899",
             "wd:Q900800",  "wd:Q3819233", "wd:Q588936",
             "wd:Q181898", "wd:Q185357", "wd:Q210028", "wd:Q552456", "wd:Q14946524",
             "wd:Q124131", "wd:Q3155522", "wd:Q133900", "wd:Q14946524",
             "wd:Q192005", "wd:Q452648", "wd:Q139143", "wd:Q3680646", "wd:Q648191"))
QIDup <- unique(c(QIDup, QIDdown))

#除外リスト
Ex <- c("wd:Q82264", "wd:Q61951", "wd:Q1433061", "wd:Q229367", "wd:Q747713", 
        "wd:Q79782", "wd:Q13406206", "wd:Q3929317", "wd:Q16525404",
        "wd:Q9363879", "wd:Q9363879", "wd:Q44432", "wd:Q496098")
```

## search the upper-hieracry

```{r}
#df <- readRDS("./00_Input/Relation_P31_P279_df.Rds")
colnames(df) <- c("Subject", "Property", "Object")
#head(df)

######################################################################
######################################################################
#上位探索 subClassOf & instanceOf
Data <- c(); x <- 1; Query <- QIDup; DepN <- 20
repeat{
message("Depth: ", x)
b1 <- df[df$Subject %in% Query,]
if(dim(b1)[1] == 0){break}
b1$Depth <- paste0("up", formatC(x, flag = "0", width = "2"))
Data <- rbind(Data, b1)
Query <- b1$Object
if(x == DepN){break}
x <- x + 1
}
######################################################################
#下位探索 subClassOf
#カウント
######################################################################
if(F){
DatSubClassOfDownCount <- c()
for(n in 1:length(QIDdown)){
DatSubClassOfDown <- c(); x <- 1; DepN <- 20; Query <- QIDdown[n]
message("Query: ", Query)
repeat{
print(x)
Query <- Query[!(Query %in% Ex)]
b1 <- df[df$Object %in% Query,]
b1 <- b1[b1$Property == "wdt:P279",]
if(dim(b1)[1] == 0){
  if(is.null(DatSubClassOfDown)){
  DatSubClassOfDownCount[n] <- 0
  break 
  }else{
  rownames(DatSubClassOfDown) <- 1:nrow(DatSubClassOfDown)
  DatSubClassOfDown$triple <- paste0(DatSubClassOfDown$Subject, ".", 
                                     DatSubClassOfDown$Property, ".", 
                                     DatSubClassOfDown$Object)
  DatSubClassOfDown <- DatSubClassOfDown[as.numeric(rownames(unique(DatSubClassOfDown["triple"]))),]
  DatSubClassOfDownCount[n] <- nrow(DatSubClassOfDown)
  break
  }
}
b1$Depth <- paste0("down", formatC(x, flag = "0", width = "2"))
DatSubClassOfDown <- rbind(DatSubClassOfDown, b1)
Query <- b1$Subject
if(x == DepN){
  rownames(DatSubClassOfDown) <- 1:nrow(DatSubClassOfDown)
  DatSubClassOfDown$triple <- paste0(DatSubClassOfDown$Subject, ".", 
                                     DatSubClassOfDown$Property, ".", 
                                     DatSubClassOfDown$Object)
  DatSubClassOfDown <- DatSubClassOfDown[as.numeric(rownames(unique(DatSubClassOfDown["triple"]))),]
  DatSubClassOfDownCount[n] <- nrow(DatSubClassOfDown)
  break}
x <- x + 1
Query <- Query[!(Query %in% Ex)]
}}

#取得数
data.frame(QIDdown, DatSubClassOfDownCount)
}

######################################################################
######################################################################
#下位探索 subClassOf
#取得
DatSubClassOfDown <- c(); x <- 1; Query <- QIDdown; DepN <- 20
repeat{
message("Depth: ", x)
Query <- Query[!(Query %in% Ex)]
b1 <- df[df$Object %in% Query,]
b1 <- b1[b1$Property == "wdt:P279",]
if(dim(b1)[1] == 0){break}
b1$Depth <- paste0("down", formatC(x, flag = "0", width = "2"))
DatSubClassOfDown <- rbind(DatSubClassOfDown, b1)
Query <- b1$Subject
if(x == DepN){break}
x <- x + 1
Query <- Query[!(Query %in% Ex)]
}

######################################################################
######################################################################
#下位探索 instanceOf
DatInstanceOfDown <- c(); x <- 1; Query <- QIDdown; DepN <- 20
repeat{
message("Depth: ", x)
b1 <- df[df$Object %in% Query,]
b1 <- b1[b1$Property == "wdt:P31",]
if(dim(b1)[1] == 0){break}
b1$Depth <- paste0("down", formatC(x, flag = "0", width = "2"))
DatInstanceOfDown <- rbind(DatInstanceOfDown, b1)
Query <- b1$Subject
if(x == DepN){break}
x <- x + 1
Query <- Query[!(Query %in% Ex)]
}

######################################################################
#詳細
######################################################################
table(DatSubClassOfDown$Depth)
table(DatInstanceOfDown$Depth)

######################################################################
######################################################################
#グラフの結合
Dat <- rbind(Data, DatSubClassOfDown)
Dat <- rbind(Dat, DatInstanceOfDown)

#remove
table(Dat$Depth)
#Dat <- Dat[!(Dat$Depth %in% c("down07", "down08", "down09", "down10", "down11", "down12", "down13")),]
Dat <- Dat[,-4]
#Dat <- rbind(DatSubClassOfDown, DatInstanceOfDown)
######################################################################
######################################################################
#create dir
if(!dir.exists("01_Wiki_Out")){dir.create("01_Wiki_Out")}
######################################################################
head(Dat); dim(Dat)
rownames(Dat) <- 1:nrow(Dat)
colnames(Dat) <- c("subject", "property", "parentClass")
Dat$triple <- paste0(Dat$subject, ".", Dat$property, ".", Dat$parentClass)
Dat <- Dat[as.numeric(rownames(unique(Dat["triple"]))),]
Dat <- Dat[,-ncol(Dat)]
head(Dat); dim(Dat)
######################################################################
######################################################################
length(unique(c(Dat$subject, Dat$parentClass)))
#saveRDS(Dat, "./01_Wiki_Out/Wiki_Dat_up_down.Rds")
######################################################################
######################################################################
######################################################################
##Read Data
#rm(list=ls())
#Dat <- readRDS("./01_Wiki_Out/Wiki_Dat_up_down.Rds")

#if(!exists("Wikilabels")){ Wikilabels <- data.frame(readRDS("./00_Input/WikiLab.Rds")) }
Wikilabels00 <- Wikilabels[Wikilabels$Subject %in% unique(c(Dat$subject, Dat$parentClass)),]

######################################################################
######################################################################
#Add labels
library(agGraphSearch)
library(magrittr)

Dat00 <- MergeWikiData(Data=Dat, Labels=Wikilabels00)
#saveRDS(Dat00, "./01_Wiki_Out/Wiki_Dat00.Rds")
#Dat00 <- readRDS("./01_Wiki_Out/Wiki_Dat00.Rds")
FileName <- paste0("agVisNetwork_process_", format(Sys.time(), "%y%m%d-%H%M%S"),".html")

head(Dat00); dim(Dat00); table(Dat00$property)
table(Dat00$property)
Dat01 <- Dat00
head(Dat01)

#Rename
d <- unique(c(Dat01[,c("subjectLabel")][grepl("wd:", Dat01[,c("subjectLabel")])], 
              Dat01[,c("parentClass")][grepl("wd:", Dat01[,c("parentClass")])]))
length(d)

#OECUプロキシ設定
if(T){
proxy_url = "http://wwwproxy.osakac.ac.jp:8080"
Sys.setenv("http_proxy" = proxy_url)
Sys.setenv("https_proxy" = proxy_url)
Sys.setenv("ftp_proxy" = proxy_url)
}

#Wikidataの最新ラベルに変更する
for(n in 1:length(d)){
#n <-1
message("Progress: ", n, " / ", length(d))
a <- wikiQID2Label(EntityQID = d[n])
if(!is.na(a$entityNamej[1])){
Dat01$subjectLabel[Dat01$subject == d[n]] <- a$entityNamej[1]
Dat01$parentClassLabel[Dat01$parentClass == d[n]] <- a$entityNamej[1] 
}else{}}

head(Dat01)
readr::write_excel_csv(Dat01, file = paste0("./01_Wiki_Out/", sub(".html", ".csv", FileName)), col_names = T)
#Dat01 <- data.frame(readr::read_csv(paste0("./01_Wiki_Out/", sub(".html", ".csv", FileName)), col_names = T))

#グラフ可視化
agVisNetwork(Graph=Dat01,
             Selected=NULL, 
             Browse=TRUE, 
             Output=TRUE,
             FilePath=FileName)

system(paste0("mv ", FileName, " ./01_Wiki_Out"))

#ツリー可視化
agJsTree(Data=Dat01, 
         TopClass="エンティティ.wd:Q35120", 
         Brouse=TRUE, SaveHtmlFile=TRUE, FileName=NULL, Output=NULL)



head(Dat01)
library(jsTree)

Dat02 <- Dat01
Dat02$X <- paste0(Dat02$subjectLabel, ".", Dat02$subject)
Dat02$Y <- paste0(Dat02$parentClassLabel, ".", Dat02$parentClass)
Dat03 <- Dat02[,c("X", "Y")]
head(Dat03)

DatDF <- c()
TopClass <- "エンティティ.wd:Q35120"
BottomClass <- unique(Dat03$X)[!(unique(Dat03$X) %in% unique(Dat03$Y))]

graphList <- data.frame(from=Dat03$X, to=Dat03$Y, stringsAsFactors = F)
D00 <- igraph::graph_from_edgelist(as.matrix(graphList), directed = T)

#最短パスの取得
for(n in seq_len(length(BottomClass))){
#n <- 1
a <- igraph::as_ids(igraph::shortest_paths(D00, 
                       from = BottomClass[n], 
                       to = TopClass)$vpath[[1]])
b <- paste(a[length(a):1], collapse='/')
DatDF <- c(DatDF, b)
}


jsTree::jsTree(DatDF, width="125%", height="150%")
jsTree::jsTree(DatDF, width="125%", height="150%") %>%
  htmlwidgets::saveWidget(sub("agVisNetwork_process_", "agJsTree_Wikidata_Process_",  FileName))
system(paste0("mv ", sub("agVisNetwork_process_", "agJsTree_Wikidata_Process_",  FileName), " ./01_Wiki_Out"))

```


# Session information {.unnumbered}
```{r sessionInfo, echo=FALSE}
sessionInfo()
```
