---
title: "Workflow to use agGraphSearch"
shorttitle: "WF-002: match labels to the wikidata via SPARQL"
author: 
- name: Satoshi Kume
date: "`r Sys.Date()`"
graphics: no
package: agGraphSearch, knitr, SPARQL
output:
  BiocStyle::html_document:
  toc_float: true
vignette: >
  %\VignetteIndexEntry{Workflow to use agGraphSearch}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
  %\VignetteDepends{agGraphSearch}
---

```{r style, echo = FALSE, results = 'asis', message=FALSE}
BiocStyle::markdown()
```

**Last modified:** `r file.info("BioImageDbs.Rmd")$mtime`<br />
**Compiled**: `r date()`

# Getting started

Once `r Rpackage("agGraphSearch")` is installed, it can be loaded by the following command.

```{r library, message=FALSE}
library("agGraphSearch")
```

This workflow can be skipped. The next workflow should be started. 

# Read the csv files

```{r echo=TRUE, eval=FALSE}
lab <- data.frame(readr::read_csv("./00_Input/words.lab.csv", col_names = F))
```

if the WF-001 is skipped, start with the command as follows.

```{r echo=TRUE, eval=FALSE}
f <- system.file("extdata", "words.lab.csv", package="agGraphSearch")
lab <- data.frame(readr::read_csv(f, col_names = T))
```


# Session information {.unnumbered}
```{r sessionInfo, echo=FALSE}
sessionInfo()
```
