---
title: "Workflow to use agGraphSearch and Wikidata RDF: WF-003"
shorttitle: "WF-003: match labels to the wikidata via SPARQL"
author:
  - name: Satoshi Kume
date: "`r Sys.Date()`"
graphics: no
package: agGraphSearch, knitr, SPARQL
output:
  BiocStyle::html_document:
  toc_float: true
vignette: >
  %\VignetteEncoding{UTF-8}
  %\VignetteDepends{agGraphSearch}
  %\VignetteIndexEntry{Workflow to use agGraphSearch: WF-003}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

```{r style, echo = FALSE, results = 'asis', message=FALSE}
BiocStyle::markdown()
```

**Last modified:** `r file.info("agGraphSearch-WF-002.Rmd")$mtime`<br />
**Compiled**: `r date()`

# Getting started

Once `r Rpackage("agGraphSearch")` is installed, it can be loaded by the following command.

```{r library, message=FALSE}
library("agGraphSearch")
```

This workflow can be skipped. The next workflow should be started. 

# prepare QIDs

```{r echo=TRUE, eval=FALSE}
#変化 (wd:Q1150070)
#過程 (wd:Q3249551)
#行為 (wd:Q1914636)
#物理的プロセス (wd:Q17320256)
#プロセス機能 (wd:Q900800)
#物理現象 (wd:Q1293220)
#熱力学過程 (wd:Q213016)
#技術 (wd:Q2695280)
#製造プロセス  (wd:Q1408288)
#工学的プロセス (wd:Q10843872)
#自然過程 (wd:Q13878858)
#計画プロセス (wd:Q104637332)
#材料加工 (wd:Q104637425)
#成形プロセス (wd:Q1363994)
#化学過程 (wd:Q2281940)
#化学反応 (wd:Q36534)
#物質の変換 (wd:Q3537517)
#重合反応 (wd:Q181898)
#連鎖反応 (化学反応) (wd:Q1739960)

#Process
QID <- c("wd:Q1150070", "wd:Q3249551", "wd:Q1914636", 
         "wd:Q17320256", "wd:Q900800", "wd:Q1293220", 
         "wd:Q213016", "wd:Q2695280", "wd:Q1408288",
         "wd:Q10843872", "wd:Q13878858", "wd:Q104637332",
         "wd:Q104637425", "wd:Q1363994", "wd:Q2281940",
         "wd:Q36534", "wd:Q3537517", "wd:Q181898", "wd:Q1739960")

```

## search the upper-hieracry

```{r}
rm(list=ls())
Wikilabels <- readRDS("./00_Input/WikiLab.Rds")
head(Wikilabels <- data.frame(Wikilabels))

df <- readRDS("./00_Input/Relation_P31_P279_df.Rds")
colnames(df) <- c("Subject", "Property", "Object")
head(df)
######################################################################
######################################################################
#上位探索
Dat <- c(); x <- 1; Query <- QID
repeat{
print(x)
b1 <- df[df$Subject %in% Query,]
if(dim(b1)[1] == 0){break}
Dat <- rbind(Dat, b1)
Query <- b1$Object
if(x == 50){break}
x <- x + 1
}
######################################################################
######################################################################
#create dir
if(!dir.exists("01_Wiki_Out")){dir.create("01_Wiki_Out")}
######################################################################
head(Dat); dim(Dat)
rownames(Dat) <- 1:nrow(Dat)
colnames(Dat) <- c("subject", "property", "parentClass")
Dat$triple <- paste0(Dat$subject, ".", Dat$property, ".", Dat$parentClass)
Dat <- Dat[as.numeric(rownames(unique(Dat["triple"]))),]
Dat <- Dat[,-ncol(Dat)]
head(Dat); dim(Dat)
length(unique(c(Dat$subject, Dat$parentClass)))
saveRDS(Dat, "./01_Wiki_Out/Wiki_Dat.Rds")
######################################################################
######################################################################
#Add labels
library(agGraphSearch)
Dat00 <- MergeWikiData(Data=Dat, Labels=Wikilabels)
FileName <- paste0("agVisNetwork_process_", format(Sys.time(), "%y%m%d-%H%M%S"),".html")

head(Dat00); dim(Dat00); table(Dat00$property)
table(Dat00$property)



if(T){
agVisNetwork(Graph=Dat00,
             Selected=NULL, 
             Browse=TRUE, 
             Output=TRUE,
             FilePath=FileName)
}



```


# Session information {.unnumbered}
```{r sessionInfo, echo=FALSE}
sessionInfo()
```
